---
- name: Install the setup of various tools
  hosts: all
  vars_files:
    - default.config.yml
  vars:
    - user: mroberts
    - docker_users: "{{ user }}"
  # pre_tasks:
  roles:
    - role: geerlingguy.docker
      tags: ['docker']
      become: true
  tasks:
    - name: Set up Zsh
      import_tasks: tasks/zsh.yml
      tags: ['zsh']

    - name: Setup Terraform and Terragrunt
      import_tasks: tasks/terraform.yml
      tags: ['terraform']

    - name: Initial setup of Neovim
      import_tasks: tasks/nvim.yml
      tags: ['neovim']
      become: true

    - name: Setup of Jenkins local testing
      import_tasks: tasks/jenkins-local.yml
      tags: ['jenkins:local']
      become: true

    - name: Setup of Ruby
      import_tasks: tasks/ruby.yml
      tags: ['ruby']

    - name: Setup of additional tools
      import_tasks: tasks/tools.yml
      tags: ['tools']
