---
# For practicing with this kind of setup: 
# https://github.com/steven-terrana/jte-local-demo
- name: jenkins-local | install necessary packages
  apt:
    name: "{{ item }}"
  loop:
    - just
   #- watchexec # watchexec is not a thing in ubuntu (apt)
