---
- name: add stable neovim repository
  apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: update apt-get
  apt:
    update_cache: yes

- name: install neovim
  apt:
    name: neovim

# Need ripgrep to use fzf with neovim
# Need build-essential to install C dependencies for LSP
- name: install dependencies for neovim config
  apt:
    name: 
      - ripgrep
      - build-essential
