---
- name: add stable neovim repository
  apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: update apt-get
  apt:
    update_cache: true

- name: install neovim
  apt:
    name: neovim

# Need ripgrep to use fzf with neovim
# Need build-essential to install C dependencies for LSP
- name: install package dependencies for neovim config
  apt:
    name:
      - ripgrep
      - build-essential

- name: check if nvm is installed
  stat:
    path: "{{ ansible_env.HOME }}/.nvm"
  register: nvm_path

- name: install nvm  # noqa: command-instead-of-module
  shell: |
    set -o pipefail
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  become: true
  become_method: sudo
  become_user: "{{ user }}"
  when: nvm_path.stat.exists is false

- name: install latest node version
  shell: "source /home/{{ user }}/.zshrc && nvm install node"
  args:
    executable: /usr/bin/zsh
  become: true
  become_method: sudo
  become_user: "{{ user }}"
