# Steps from here: https://github.com/tfutils/tfenv#manual
---
- name: Clone tfenv repo to ~/.tfenv
  git:
    repo: https://github.com/tfutils/tfenv.git
    dest: "/home/{{ user }}/.tfenv"
    depth: 1

- name: add tfenv executable to path for WSL
  lineinfile:
    path: "/home/{{ user }}/.zshrc"
    line: export PATH=$PATH:$HOME/.tfenv/bin

    #- name: install terraform version

- name: install tgswitch for terragrunt versioning
  get_url:
    url: https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh
    dest: "/home/{{ user }}/"
    mode: '0755'

- name: install tgswitch
  script: "/home/{{ user }}/install.sh -b $HOME/.bin"

- name: export tgswitch to path
  lineinfile:
    path: "/home/{{ user }}/.zshrc"
    line: export PATH=$PATH:$HOME/.bin
   
