# Steps from here: https://github.com/tfutils/tfenv#manual
---
- name: Clone tfenv repo to ~/.tfenv  # noqa latest[git]
  git:
    repo: https://github.com/tfutils/tfenv.git
    dest: "/home/{{ user }}/.tfenv"
    depth: 1
    update: true

- name: Add tfenv executable to path for WSL
  lineinfile:
    path: "/home/{{ user }}/.zshrc"
    line: export PATH=$PATH:$HOME/.tfenv/bin

# - name: install terraform version

- name: Install tgswitch for terragrunt versioning
  get_url:
    url: https://raw.githubusercontent.com/warrensbox/tgswitch/release/install.sh
    dest: "/home/{{ user }}/"
    mode: '0755'

- name: Install tgswitch
  script: "/home/{{ user }}/install.sh -b $HOME/.bin"

- name: Export tgswitch to path
  lineinfile:
    path: "/home/{{ user }}/.zshrc"
    line: export PATH=$PATH:$HOME/.bin
